{
 "title": "Demo Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "traces_span_metrics_duration_milliseconds_bucket"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard shows RED metrics for the selected service, as generated by the spanmetrics connector in the OpenTelemetry Collector.\nIf the selected service emits logs, the logs will also be displayed.\nCustom metrics generated by some services are also displayed.\n<br>\nChart panels may require 5 minutes after the Demo is started before rendering data."
   }
  },
  { "title": "Spanmetrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Latency for ${service}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile999"
    }
   ]
  },
  {
   "title": "Error Rate for ${service} by span name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": " sum by (span_name) (rate(traces_span_metrics_calls_total{status_code=\"STATUS_CODE_ERROR\", service_name=\"${service}\"}[$__rate_interval]))",
     "legendFormat": "{{ span_name }}"
    }
   ]
  },
  {
   "title": "Requests Rate for ${service} by span name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (span_name) (rate(traces_span_metrics_duration_milliseconds_count{service_name=\"${service}\"}[$__rate_interval]))",
     "legendFormat": "{{ span_name }}"
    }
   ]
  },
  { "title": "Application Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "${service} Log entries by Severity",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 20 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "search source=otel\n| where resource.service.name=\"${service}\"\n| stats count() by severity.text",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "${service} Logs (100 recent entries)",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 20 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "search source=otel\n| where resource.service.name=\"${service}\"| sort - observedTimestamp | head 100",
     "timeField": "observedTimestamp"
    }
   ]
  },
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Python services (CPU%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_runtime_cpython_cpu_time_seconds_total{type=~\"system\"}[$__rate_interval])*100",
     "legendFormat": "{{job}} ({{type}})"
    },
    {
     "expr": "rate(process_runtime_cpython_cpu_time_seconds_total{type=~\"user\"}[$__rate_interval])*100",
     "legendFormat": "{{job}} ({{type}})"
    }
   ]
  },
  {
   "title": "Python services (Memory)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_cpython_memory_bytes{type=\"rss\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Recommendations Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "rate(app_recommendations_counter_total{recommendation_type=\"catalog\"}[$__rate_interval])",
     "legendFormat": "recommendations"
    }
   ]
  },
  {
   "title": "Quote Service batch span processor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "rate(otel_trace_span_processor_spans{job=\"quote\"}[2m])*120",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}
{
 "title": "Cart Service Exemplars",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard shows the use of metric exemplars.\nExemplars can be used to look up a trace in Jaeger.\nOnly the most recent exemplars may still be available in Jaeger.\n<br>\nChart panels may require 5 minutes after the Demo is started before rendering data."
   }
  },
  { "title": "GetCart Exemplars", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "GetCart Latency Heatmap with Exemplars",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by(le) (rate(app_cart_get_cart_latency_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "95th Pct Cart GetCart Latency with Exemplars",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(app_cart_get_cart_latency_bucket[$__rate_interval])))",
     "legendFormat": "p95 GetCart"
    }
   ]
  },
  { "title": "AddItem Exemplars", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "AddItem Latency Heatmap with Exemplars",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by(le) (rate(app_cart_add_item_latency_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "95th Pct Cart AddItem Latency with Exemplars",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(app_cart_add_item_latency_bucket[$__rate_interval])))",
     "legendFormat": "p95 AddItem"
    }
   ]
  }
 ]
}
{
 "title": "Opentelemetry Collector Data Flow",
 "description": "otelcol metrics dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_version",
    "label": "service_version",
    "query": {
     "query": "query_result(sum(otelcol_process_uptime{}) by (service_version))\n"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard is used to understand the data flows for the OpenTelemetry Collector's metrics and traces pipelines.\n<br>\nChart panels may require 5 minutes after the Demo is started before rendering data."
   }
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Instance",
   "type": "stat",
   "description": "Otel Collector Instance",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(otelcol_process_cpu_seconds_total{service_instance_id=~\".*\"}) by (service_instance_id))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu",
   "type": "gauge",
   "description": "otelcol_process_cpu_seconds",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(otelcol_process_cpu_seconds_total{}[$__rate_interval])*100) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "description": "Memory Rss\navg(otelcol_process_memory_rss{}) by (instance)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(otelcol_process_memory_rss{}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 3 },
   "options": {
    "content": "## Opentelemetry Collector Data Ingress/Egress\n\n`service_version:` ${service_version}\n\n`opentelemetry collector:` contrib\n\n"
   }
  },
  { "title": "Trace Pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Export Ratio",
   "type": "gauge",
   "description": "(avg(sum by(job) (rate(otelcol_exporter_sent_spans{}[$__range]))) / avg(sum by(job) (rate(otelcol_receiver_accepted_spans{}[$__range])))) ",
   "gridPos": { "h": 19, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg(sum by(job) (rate(otelcol_exporter_sent_spans_total{}[$__range]))) / avg(sum by(job) (rate(otelcol_receiver_accepted_spans_total{}[$__range])))) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "nodeGraph",
   "gridPos": { "h": 11, "w": 21, "x": 3, "y": 8 },
   "targets": [
    {
     "expr": "label_join(label_join(\n(rate(otelcol_receiver_accepted_spans_total{}[$__interval]))\n, \"id\", \"\", \"transport\", \"receiver\")\n, \"title\", \"\", \"transport\", \"receiver\")\n\nor\n\nlabel_replace(label_replace(\nsum by(service_name) (rate(otelcol_receiver_accepted_spans_total{}[$__interval]))\n, \"id\", \"processor\", \"dummynode\", \"\")\n, \"title\", \"processor\", \"dummynode\", \"\")\n\nor\nlabel_replace(label_replace(\n(rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n, \"id\", \"$0\", \"processor\", \".*\")\n, \"title\", \"$0\", \"processor\", \".*\")\n\nor\nlabel_replace(label_replace(\nsum by(exporter) (rate(otelcol_exporter_sent_spans_total{}[$__interval]))\n, \"id\", \"exporter\", \"dummynode\", \"\")\n, \"title\", \"exporter\", \"dummynode\", \"\")\n        \nor\nlabel_replace(label_replace(\nsum by(exporter) (rate(otelcol_exporter_sent_spans_total{}[$__interval]))\n, \"id\", \"$0\", \"exporter\", \".*\")\n, \"title\", \"$0\", \"exporter\", \".*\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(\nlabel_replace(label_join(\n(rate(otelcol_receiver_accepted_spans_total{}[$__interval]))\n\n ,\"source\",\"\",\"transport\",\"receiver\")\n,\"target\",\"processor\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")\n\n  or\n\n  label_join(\nlabel_replace(label_replace(\n  (rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n ,\"source\",\"processor\",\"\",\"\")\n,\"target\",\"$0\",\"processor\",\".*\")\n,\"id\",\"-\",\"source\",\"target\")\n\nor\n  label_join(\nlabel_replace(label_replace(\n    (rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n ,\"source\",\"$0\",\"processor\",\".*\")\n,\"target\",\"exporter\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")\n\nor\n  label_join(\nlabel_replace(label_replace(\n   (rate(otelcol_exporter_sent_spans_total{}[$__interval]))\n ,\"source\",\"exporter\",\"\",\"\")\n,\"target\",\"$0\",\"exporter\",\".*\")\n,\"id\",\"-\",\"source\",\"target\")\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted",
   "type": "stat",
   "description": "Spans Accepted by Receiver and Transport",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans_total{}[$__rate_interval])) by (receiver,transport)",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "gauge",
   "description": "Total Spans Accepted ",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans_total{}[$__rate_interval])) ",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Batch",
   "type": "stat",
   "description": "Total Batch Processed",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_batch_batch_send_size_sum{}[$__rate_interval]))  by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans_total{}[$__interval])) ",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Sent",
   "type": "stat",
   "description": "Sent by Exporter",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans_total{}[$__rate_interval])) by (exporter)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Refused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans_total{}[$__rate_interval])) by (receiver,transport)",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "gauge",
   "description": "Total Spans Accepted ",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans_total{}[$__rate_interval])) ",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "gauge",
   "description": "otelcol_exporter_send_failed_spans",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans_total{}[$__rate_interval])) ",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "description": "Sent by Exporter\notelcol_exporter_send_failed_spans",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans_total{}[$__rate_interval])) by (exporter)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  { "title": "Metrics Pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Export Ratio",
   "type": "gauge",
   "description": "avg(sum by(job) (rate(otelcol_exporter_sent_metric_points{}[$__range]))) versus avg(sum by(job) (rate(otelcol_receiver_accepted_metric_points{}[$__range])))",
   "gridPos": { "h": 19, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( avg(sum by(job) (rate(otelcol_exporter_sent_metric_points_total{}[$__range]))) /avg(sum by(job) (rate(otelcol_receiver_accepted_metric_points_total{}[$__range]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "nodeGraph",
   "description": "Metrics Signalling Pipelines",
   "gridPos": { "h": 11, "w": 21, "x": 3, "y": 28 },
   "targets": [
    {
     "expr": "\nlabel_join(label_join(\n(rate(otelcol_receiver_accepted_metric_points_total{}[$__interval]))\n, \"id\", \"\", \"transport\", \"receiver\")\n, \"title\", \"\", \"transport\", \"receiver\")\n\nor\n\nlabel_replace(label_replace(\nsum by(service_name) (rate(otelcol_receiver_accepted_spans_total{}[$__interval]))\n, \"id\", \"processor\", \"dummynode\", \"\")\n, \"title\", \"processor\", \"dummynode\", \"\")\n\n\n\nor\nlabel_replace(label_replace(\n(rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n, \"id\", \"$0\", \"processor\", \".*\")\n, \"title\", \"$0\", \"processor\", \".*\")\n\n\n\n\n\nor\nlabel_replace(label_replace(\nsum (rate(otelcol_exporter_sent_metric_points_total{}[$__interval]))\n, \"id\", \"exporter\", \"dummynode\", \"\")\n, \"title\", \"exporter\", \"dummynode\", \"\")\n\nor\nlabel_replace(label_replace(\nsum by(exporter) (rate(otelcol_exporter_sent_metric_points_total{}[$__interval]))\n, \"id\", \"$0\", \"exporter\", \".*\")\n, \"title\", \"$0\", \"exporter\", \".*\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(\nlabel_replace(label_join(\n(rate(otelcol_receiver_accepted_metric_points_total{}[$__interval]))\n\n,\"source\",\"\",\"transport\",\"receiver\")\n,\"target\",\"processor\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")\n\n\nor\n\nlabel_join(\nlabel_replace(label_replace(\n(rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n,\"source\",\"processor\",\"\",\"\")\n,\"target\",\"$0\",\"processor\",\".*\")\n,\"id\",\"-\",\"source\",\"target\")\n\n\n\n\n\nor\n\n\nlabel_join(\nlabel_replace(label_replace(\n(rate(otelcol_processor_batch_batch_send_size_count{}[$__interval]))\n,\"source\",\"$0\",\"processor\",\".*\")\n,\"target\",\"exporter\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")\n\nor\nlabel_join(\nlabel_replace(label_replace(\n(rate(otelcol_exporter_sent_metric_points_total{}[$__interval]))\n,\"source\",\"exporter\",\"\",\"\")\n,\"target\",\"$0\",\"exporter\",\".*\")\n,\"id\",\"-\",\"source\",\"target\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted",
   "type": "stat",
   "description": "otelcol_receiver_accepted_metric_points",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_metric_points_total{}[$__rate_interval])) by (receiver,transport)",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "gauge",
   "description": "otelcol_receiver_accepted_metric_points\nTotal Accepted ",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_metric_points_total{}[$__rate_interval])) ",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Batch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_batch_batch_send_size_sum{}[$__rate_interval]))  by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "gauge",
   "description": "Total Export ",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_metric_points_total{}[$__rate_interval])) ",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Sent",
   "type": "stat",
   "description": "Sent by Exporter",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_metric_points_total{}[$__rate_interval])) by (exporter) ",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Refused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_refused_metric_points_total{}[$__rate_interval])) by (receiver,transport)",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Total ",
   "type": "gauge",
   "description": "Total Refused \nsum(rate(otelcol_receiver_refused_metric_points{}[$__rate_interval])) ",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_refused_metric_points_total{}[$__rate_interval])) ",
     "legendFormat": "{{receiver}}-{{transport}}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "gauge",
   "description": "Total Failed Export ",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_metric_points_total{}[$__rate_interval])) ",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "description": "Sent by Exporter\notelcol_exporter_send_failed_metric_points",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_metric_points_total{}[$__rate_interval])) by (exporter)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  { "title": "Prometheus Scrape", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Exported/Scraped",
   "type": "gauge",
   "description": "otelcol prometheus exporter 8888 export rate versus prometheus scrape metrics",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum_over_time(scrape_samples_scraped{job=\"otel-collector\"}[$__range])/ count_over_time(scrape_samples_scraped{job=\"otel-collector\"}[$__range])/(5*30)) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(rate(otelcol_exporter_sent_metric_points_total{exporter=\"prometheus\"}[$__rate_interval])) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Samples Scraped",
   "type": "stat",
   "description": "sum_over_time(scrape_samples_scraped[$__range])/ count_over_time(scrape_samples_scraped[$__range])",
   "gridPos": { "h": 9, "w": 5, "x": 3, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(scrape_samples_scraped[$__range])/ count_over_time(scrape_samples_scraped[$__range])/(5*30)",
     "legendFormat": "{{job}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "gauge",
   "description": "scrape_samples_scraped{job!=\"\"}\nTotal Samples Scraped",
   "gridPos": { "h": 9, "w": 3, "x": 8, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(scrape_samples_scraped[$__range])/ count_over_time(scrape_samples_scraped[$__range])/(5*30)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "nodeGraph",
   "gridPos": { "h": 9, "w": 8, "x": 11, "y": 48 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(\nsum (scrape_samples_scraped{job!=\"\"}) by (instance)\n, \"id\", \"$0\", \"instance\", \".*\")\n, \"title\", \"$0\", \"instance\", \".*\")\n,\"mainstat\",\"\",\"\",\"\")\n\nor \n\nlabel_replace(label_replace(label_replace(\nsum (scrape_samples_scraped{job!=\"\"})\n, \"id\", \"prometheus\", \"\", \"\")\n, \"title\", \"prometheus\", \"\", \"\")\n,\"mainstat\",\"\",\"\",\"\")\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(\nlabel_replace(label_replace(\nsum (scrape_samples_scraped{job!=\"\"}) by (instance)\n,\"source\",\"$0\",\"instance\",\".*\")\n,\"target\",\"prometheus\",\"\",\"\")\n,\"id\",\"-\",\"source\",\"target\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "description": "Sent by Exporter",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 48 },
   "options": {
    "content": "\n \n## Prometheus Config\n\n`evaluation_interval:` 30s\n\n`scrape_interval:` 5s"
   }
  }
 ]
}
{
 "title": "OpenTelemetry Collector",
 "description": "Visualize OpenTelemetry (OTEL) collector metrics (tested with OTEL contrib v0.113.0)",
 "tags": [
  "opentelemetry",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(otelcol_process_uptime_total,job)"
    }
   },
   { "name": "minstep", "label": "Min step", "query": "10s,30s,1m,5m" },
   { "name": "metric", "label": "Base metric", "query": "Rate : rate, Count : increase" },
   { "name": "receiver", "label": "Receiver", "query": { "query": "label_values(receiver)" } },
   { "name": "processor", "label": "Processor", "query": { "query": "label_values(processor)" } },
   { "name": "exporter", "label": "Exporter", "query": { "query": "label_values(exporter)" } },
   {
    "name": "grouping",
    "label": "Additional groupping",
    "query": "None (basic metrics) :  , By transport (detailed metrics) : \\,transport, By service instance id : \\,service_instance_id"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard uses the metrics generated by the OpenTelemetry Collector.\nIt is used to understand the overall performance and health of the OpenTelemetry Collector.\n<br>\nChart panels may require 5 minutes after the Demo is started before rendering data."
   }
  },
  { "title": "Receivers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Spans ${metric:text}",
   "type": "timeseries",
   "description": "Accepted: count/rate of spans successfully pushed into the pipeline.\nRefused: count/rate of spans that could not be pushed into the pipeline.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_receiver_accepted_spans_total{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Accepted: {{receiver}} {{transport}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_receiver_refused_spans_total{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Refused: {{receiver}} {{transport}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Metric Points ${metric:text}",
   "type": "timeseries",
   "description": "Accepted: count/rate of metric points successfully pushed into the pipeline.\nRefused: count/rate of metric points that could not be pushed into the pipeline.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_receiver_accepted_metric_points_total{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Accepted: {{receiver}} {{transport}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_receiver_refused_metric_points_total{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Refused: {{receiver}} {{transport}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Log Records ${metric:text}",
   "type": "timeseries",
   "description": "Accepted: count/rate of log records successfully pushed into the pipeline.\nRefused: count/rate of log records that could not be pushed into the pipeline.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_receiver_accepted_log_records_total{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Accepted: {{receiver}} {{transport}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_receiver_refused_log_records_total{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Refused: {{receiver}} {{transport}} {{service_instance_id}}"
    }
   ]
  },
  { "title": "Processors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Batch Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_processor_batch_batch_send_size_count{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor)",
     "legendFormat": "Batch send size count: {{processor}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_processor_batch_batch_send_size_sum{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor)",
     "legendFormat": "Batch send size sum: {{processor}}"
    }
   ]
  },
  {
   "title": "Batch Send Size Heatmap",
   "type": "heatmap",
   "description": "Number of units in the batch",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(otelcol_processor_batch_batch_send_size_bucket{processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Batch Metrics",
   "type": "timeseries",
   "description": "Number of times the batch was sent due to a size trigger. Number of times the batch was sent due to a timeout trigger.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_processor_batch_timeout_trigger_send_total {processor=~\"$processor\",job=\"$job\"}[$__rate_interval])) by (processor)",
     "legendFormat": "Batch sent due to a timeout trigger: {{processor}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_processor_batch_timeout_trigger_send{processor=~\"$processor\"}[$__rate_interval])) by (processor)",
     "legendFormat": "Batch sent due to a timeout trigger: {{processor}}"
    }
   ]
  },
  { "title": "Exporters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Spans ${metric:text}",
   "type": "timeseries",
   "description": "Sent: count/rate of spans successfully sent to destination.\nEngueue: count/rate of spans failed to be added to the sending queue.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_exporter_sent_spans_total{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Sent: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_enqueue_failed_spans{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Enqueue: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_send_failed_spans{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Failed: {{exporter}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Metric Points ${metric:text}",
   "type": "timeseries",
   "description": "Sent: count/rate of metric points successfully sent to destination.\nEngueue: count/rate of metric points failed to be added to the sending queue.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_exporter_sent_metric_points_total{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Sent: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_enqueue_failed_metric_points{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Enqueue: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_send_failed_metric_points{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Failed: {{exporter}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Log Records ${metric:text}",
   "type": "timeseries",
   "description": "Sent: count/rate of log records successfully sent to destination.\nEngueue: count/rate of log records failed to be added to the sending queue.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_exporter_sent_log_records_total{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Sent: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_enqueue_failed_log_records{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Enqueue: {{exporter}} {{service_instance_id}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_send_failed_log_records{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Failed: {{exporter}} {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Exporter Queue Size",
   "type": "timeseries",
   "description": "Current size of the retry queue (in batches)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(otelcol_exporter_queue_size{exporter=~\"$exporter\",job=\"$job\"}) by (exporter)",
     "legendFormat": "Max queue size: {{exporter}}"
    }
   ]
  },
  {
   "title": "Exporter Queue Capacity",
   "type": "timeseries",
   "description": "Fixed capacity of the retry queue (in batches)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(otelcol_exporter_queue_capacity{exporter=~\"$exporter\",job=\"$job\"}) by (exporter)",
     "legendFormat": "Queue capacity: {{exporter}}"
    }
   ]
  },
  { "title": "Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Total RSS Memory",
   "type": "timeseries",
   "description": "Total physical memory (resident set size)",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(otelcol_process_memory_rss{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Max Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "avg(otelcol_process_memory_rss{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Avg Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "min(otelcol_process_memory_rss{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Min Memory RSS {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Total Runtime Sys Memory",
   "type": "timeseries",
   "description": "Total bytes of memory obtained from the OS (see 'go doc runtime.MemStats.Sys')",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(otelcol_process_runtime_total_sys_memory_bytes{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Max Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "avg(otelcol_process_runtime_total_sys_memory_bytes{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Avg Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "min(otelcol_process_runtime_total_sys_memory_bytes{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Min Memory RSS {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Total Runtime Heap Memory",
   "type": "timeseries",
   "description": "Bytes of allocated heap objects (see 'go doc runtime.MemStats.HeapAlloc')",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(otelcol_process_runtime_heap_alloc_bytes{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Max Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "avg(otelcol_process_runtime_heap_alloc_bytes{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Avg Memory RSS {{service_instance_id}}"
    },
    {
     "expr": "min(otelcol_process_runtime_heap_alloc_bytes{job=\"$job\"}) by (job $grouping)",
     "legendFormat": "Min Memory RSS {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Total CPU user and system time in percentage",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(rate(otelcol_process_cpu_seconds_total{job=\"$job\"}[$__rate_interval])*100) by (job $grouping)",
     "legendFormat": "Max CPU usage {{service_instance_id}}"
    },
    {
     "expr": "avg(rate(otelcol_process_cpu_seconds_total{job=\"$job\"}[$__rate_interval])*100) by (job $grouping)",
     "legendFormat": "Avg CPU usage {{service_instance_id}}"
    },
    {
     "expr": "min(rate(otelcol_process_cpu_seconds_total{job=\"$job\"}[$__rate_interval])*100) by (job $grouping)",
     "legendFormat": "Min CPU usage {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Service Instance Count",
   "type": "timeseries",
   "description": "Number of service instances, which are reporting metrics",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(count(otelcol_process_cpu_seconds_total{service_instance_id=~\".*\",job=\"$job\"}) by (service_instance_id))",
     "legendFormat": "Service instance count"
    }
   ]
  },
  {
   "title": "Uptime by Service Instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(otelcol_process_uptime_total{service_instance_id=~\".*\",job=\"$job\"}) by (service_instance_id)",
     "legendFormat": "Service instance uptime: {{service_instance_id}}"
    }
   ]
  },
  {
   "title": "Service Instance Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(otelcol_process_uptime_total{service_instance_id=~\".*\",job=\"$job\"}) by (service_instance_id,service_name,service_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Data Flows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Spans Flow",
   "type": "nodeGraph",
   "description": "Receivers -> Processor(s) -> Exporters (Node Graph panel is beta, so this panel may not show data correctly).",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "# receivers\nlabel_replace(\n  label_join(\n    label_join(\n      sum(${metric:value}(\n        otelcol_receiver_accepted_spans_total{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])\n      ) by (receiver)\n      , \"id\", \"-rcv-\", \"transport\", \"receiver\"\n    )\n    , \"title\", \"\", \"transport\", \"receiver\"\n  )\n  , \"icon\", \"arrow-to-right\", \"\", \"\"\n)\n\n# dummy processor\nor\nlabel_replace(\n  label_replace(\n    label_replace(\n      (sum(rate(otelcol_process_uptime_total{job=\"$job\"}[$__interval])))\n      , \"id\", \"processor\", \"\", \"\"\n    )\n    , \"title\", \"Processor(s)\", \"\", \"\"\n  )\n  , \"icon\", \"arrow-random\", \"\", \"\"\n)\n\n# exporters\nor\nlabel_replace(\n  label_join(\n    label_join(\n      sum(${metric:value}(\n        otelcol_exporter_sent_spans_total{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])\n      ) by (exporter)\n      , \"id\", \"-exp-\", \"transport\", \"exporter\"\n    )\n    , \"title\", \"\", \"transport\", \"exporter\"\n  )\n  , \"icon\", \"arrow-from-right\", \"\", \"\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "# receivers -> processor\r\nlabel_join(\r\n    label_replace(\r\n        label_join(\r\n            (sum(rate(otelcol_receiver_accepted_spans_total{job=\"$job\"}[$__interval])) by (receiver))\r\n            ,\"source\", \"-rcv-\", \"transport\", \"receiver\"\r\n        )\r\n        ,\"target\", \"processor\", \"\", \"\"\r\n    )\r\n    , \"id\", \"-\", \"source\", \"target\"\r\n)\r\n\r\n# processor -> exporters\r\nor\r\nlabel_join(\r\n    label_replace(\r\n        label_join(\r\n            (sum(rate(otelcol_exporter_sent_spans_total{job=\"$job\"}[$__interval])) by (exporter))\r\n            , \"target\", \"-exp-\", \"transport\", \"exporter\"\r\n        )\r\n        , \"source\", \"processor\", \"\", \"\"\r\n    )\r\n    , \"id\", \"-\", \"source\", \"target\"\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metric Points Flow",
   "type": "nodeGraph",
   "description": "Receivers -> Processor(s) -> Exporters (Node Graph panel is beta, so this panel may not show data correctly).",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 64 },
   "targets": [
    {
     "expr": "# receivers\nlabel_replace(\n  label_join(\n    label_join(\n      (sum(\n        ${metric:value}(otelcol_receiver_accepted_metric_points_total{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])\n      ) by (receiver))\n      , \"id\", \"-rcv-\", \"transport\", \"receiver\"\n    )\n    , \"title\", \"\", \"transport\", \"receiver\"\n  )\n  , \"icon\", \"arrow-to-right\", \"\", \"\"\n)\n\n# dummy processor\nor\nlabel_replace(\n  label_replace(\n    label_replace(\n      (sum(rate(otelcol_process_uptime_total{job=\"$job\"}[$__interval])))\n      , \"id\", \"processor\", \"\", \"\"\n    )\n    , \"title\", \"Processor(s)\", \"\", \"\"\n  )\n  , \"icon\", \"arrow-random\", \"\", \"\"\n)\n\n# exporters\nor\nlabel_replace(\n  label_join(\n    label_join(\n      (sum(\n        ${metric:value}(otelcol_exporter_sent_metric_points_total{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])\n      ) by (exporter))\n      , \"id\", \"-exp-\", \"transport\", \"exporter\"\n    )\n    , \"title\", \"\", \"transport\", \"exporter\"\n  )\n  , \"icon\", \"arrow-from-right\", \"\", \"\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "# receivers -> processor\r\nlabel_join(\r\n    label_replace(\r\n        label_join(\r\n            (sum(rate(otelcol_receiver_accepted_metric_points_total{job=\"$job\"}[$__interval])) by (receiver))\r\n            , \"source\", \"-rcv-\", \"transport\", \"receiver\"\r\n        )\r\n        , \"target\", \"processor\", \"\", \"\"\r\n    )\r\n    , \"id\", \"-\", \"source\", \"target\"\r\n)\r\n\r\n# processor -> exporters\r\nor \r\nlabel_join(\r\n    label_replace(\r\n        label_join(\r\n            (sum(rate(otelcol_exporter_sent_metric_points_total{job=\"$job\"}[$__interval])) by (exporter))\r\n            , \"target\", \"-exp-\", \"transport\", \"exporter\"\r\n        )\r\n        , \"source\", \"processor\", \"\", \"\"\r\n    )\r\n    , \"id\", \"-\", \"source\", \"target\"\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Records Flow",
   "type": "nodeGraph",
   "description": "Receivers -> Processor(s) -> Exporters (Node Graph panel is beta, so this panel may not show data correctly).",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 64 },
   "targets": [
    {
     "expr": "# receivers\nlabel_replace(\n  label_join(\n    label_join(\n      sum(${metric:value}(\n        otelcol_receiver_accepted_log_records_total{receiver=~\"$receiver\",job=\"$job\"}[$__rate_interval])\n      ) by (receiver)\n      , \"id\", \"-rcv-\", \"transport\", \"receiver\"\n    )\n    , \"title\", \"\", \"transport\", \"receiver\"\n  )\n  , \"icon\", \"arrow-to-right\", \"\", \"\"\n)\n\n# dummy processor\nor\nlabel_replace(\n  label_replace(\n    label_replace(\n      (sum(rate(otelcol_process_uptime_total{job=\"$job\"}[$__interval])))\n      , \"id\", \"processor\", \"\", \"\"\n    )\n    , \"title\", \"Processor(s)\", \"\", \"\"\n  )\n  , \"icon\", \"arrow-random\", \"\", \"\"\n)\n\n# exporters\nor\nlabel_replace(\n  label_join(\n    label_join(\n      sum(${metric:value}(\n        otelcol_exporter_sent_log_records_total{exporter=~\"$exporter\",job=\"$job\"}[$__rate_interval])\n      ) by (exporter)\n      , \"id\", \"-exp-\", \"transport\", \"exporter\"\n    )\n    , \"title\", \"\", \"transport\", \"exporter\"\n  )\n  , \"icon\", \"arrow-from-right\", \"\", \"\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "# receivers -> processor\r\nlabel_join(\r\n    label_replace(\r\n        label_join(\r\n            (sum(rate(otelcol_receiver_accepted_log_records_total{job=\"$job\"}[$__interval])) by (receiver))\r\n            , \"source\", \"-rcv-\", \"transport\", \"receiver\"\r\n        )\r\n        , \"target\", \"processor\", \"\", \"\"\r\n    )\r\n    , \"id\", \"-edg-\", \"source\", \"target\"\r\n)\r\n\r\n# processor -> exporters\r\nor \r\nlabel_join(\r\n    label_replace(\r\n        label_join(\r\n            (sum(rate(otelcol_exporter_sent_log_records_total{job=\"$job\"}[$__interval])) by (exporter))\r\n            ,\"target\",\"-exp-\",\"transport\",\"exporter\"\r\n        )\r\n        ,\"source\",\"processor\",\"\",\"\"\r\n    )\r\n    ,\"id\",\"-edg-\",\"source\",\"target\"\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 73 },
   "options": {
    "content": "<a href=\"http://www.monitoringartist.com\" target=\"_blank\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md#metrics\">OTEL collector troubleshooting (how to enable telemetry metrics)</a> | \n<a target=\"_blank\" href=\"https://opentelemetry.io/docs/collector/scaling/\">Scaling the Collector (metrics to watch)</a> | \n<a target=\"_blank\" href=\"https://grafana.com/grafana/dashboards/15983-opentelemetry-collector/\">Installed from Grafana.com dashboards</a>"
   }
  }
 ]
}
{
 "title": "Spanmetrics Demo Dashboard",
 "description": "Spanmetrics way of demo application view.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "query_result(count by (service_name)(count_over_time(traces_span_metrics_calls_total[$__range])))"
    }
   },
   {
    "name": "span_name",
    "query": {
     "query": "query_result(sum ({__name__=~\".*traces_span_metrics_calls_total\",service_name=~\"$service\"})  by (span_name))"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard uses RED metrics generated for all services by the spanmetrics connector configured in the OpenTelemetry Collector.\n<br>\nChart panels may require 5 minutes after the Demo is started before rendering data."
   }
  },
  {
   "title": "Service Level - Throughput and Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Top 3x3 - Service Latency - quantile95",
   "type": "gauge",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(7,histogram_quantile(0.95, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])) by (le,service_name)))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Services Mean Rate over Range",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7,sum by (service_name) (rate(traces_span_metrics_calls_total{service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Services Mean ERROR Rate over Range",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7,sum(rate(traces_span_metrics_calls_total{status_code=\"STATUS_CODE_ERROR\",service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])) by (service_name))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  { "title": "span_names Level - Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Top 7 span_names and Errors  (APM Table)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(7, sum(rate(traces_span_metrics_calls_total{service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])) by (span_name,service_name)) "
    },
    {
     "expr": "topk(7, sum(rate(traces_span_metrics_calls_total{status_code=\"STATUS_CODE_ERROR\",service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])) by (span_name,service_name))"
    }
   ]
  },
  { "title": "span_name Level - Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Top 3x3 - span_name Latency - quantile95",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(7,histogram_quantile(0.95, sum(rate(traces_span_metrics_duration_milliseconds_bucket{service_name=~\"$service\", span_name=~\"$span_name\"}[$__range])) by (le,span_name)))",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "Top 7 Highest Endpoint Latencies  Mean Over Range ",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(7, sum by (span_name,service_name)(increase(traces_span_metrics_duration_milliseconds_sum{service_name=~\"${service}\", span_name=~\"$span_name\"}[5m]) / increase(traces_span_metrics_duration_milliseconds_count{service_name=~\"${service}\",span_name=~\"$span_name\"}[5m\n])))",
     "legendFormat": "{{span_name}} [{{service_name}}]"
    }
   ]
  },
  {
   "title": "Top 7 Latencies Over Range ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(7,sum by (span_name,service_name)(increase(traces_span_metrics_duration_milliseconds_sum{service_name=~\"$service\", span_name=~\"$span_name\"}[$__rate_interval]) / increase(traces_span_metrics_duration_milliseconds_count{service_name=~\"$service\", span_name=~\"$span_name\"}[$__rate_interval])))",
     "legendFormat": "[{{service_name}}]  {{span_name}}"
    }
   ]
  }
 ]
}